export const SECTORS = {
  core: {
    id: "core", label: "Core Equity", accent: "#38bdf8", accentDim: "#0c4a6e", icon: "◎",
    tagline: "Sell-side style checklist — valuation, growth, quality, balance sheet (any sector)",
    metrics: [
      { id: "forwardPE", label: "Forward P/E", description: "Next-12-month earnings multiple vs peers", unit: "x", min: 5, max: 50, step: 0.5, inverted: true, score: v => v <= 12 ? 5 : v <= 18 ? 4 : v <= 25 ? 3 : v <= 35 ? 2 : 1, bands: [{ label: "Deep value", max: 12, color: "#38bdf8" }, { label: "Fair", max: 18, color: "#7dd3fc" }, { label: "Full", max: 25, color: "#fbbf24" }, { label: "Rich", max: 35, color: "#f97316" }, { label: "Stretched", max: 99, color: "#ef4444" }] },
      { id: "pegRatio", label: "PEG Ratio", description: "P/E divided by EPS growth — growth at a reasonable price", unit: "x", min: 0, max: 4, step: 0.05, inverted: true, score: v => v <= 0.8 ? 5 : v <= 1.2 ? 4 : v <= 1.8 ? 3 : v <= 2.5 ? 2 : 1, bands: [{ label: "Compelling", max: 0.8, color: "#38bdf8" }, { label: "Attractive", max: 1.2, color: "#7dd3fc" }, { label: "Fair GARP", max: 1.8, color: "#fbbf24" }, { label: "Premium", max: 2.5, color: "#f97316" }, { label: "Overpaying growth", max: 99, color: "#ef4444" }], note: "Use 2.0 if growth not meaningful." },
      { id: "epsGrowth", label: "EPS Growth (YoY)", description: "Reported or consensus EPS growth", unit: "%", min: -30, max: 60, step: 0.5, score: v => v >= 25 ? 5 : v >= 15 ? 4 : v >= 8 ? 3 : v >= 0 ? 2 : 1, bands: [{ label: "Accelerating", min: 25, color: "#38bdf8" }, { label: "Solid", min: 15, color: "#7dd3fc" }, { label: "Steady", min: 8, color: "#fbbf24" }, { label: "Flat", min: 0, color: "#f97316" }, { label: "Contracting", min: -30, color: "#ef4444" }] },
      { id: "revenueGrowth", label: "Revenue Growth (YoY)", description: "Top-line momentum", unit: "%", min: -20, max: 50, step: 0.5, score: v => v >= 20 ? 5 : v >= 12 ? 4 : v >= 6 ? 3 : v >= 0 ? 2 : 1, bands: [{ label: "Strong", min: 20, color: "#38bdf8" }, { label: "Healthy", min: 12, color: "#7dd3fc" }, { label: "Moderate", min: 6, color: "#fbbf24" }, { label: "Slow", min: 0, color: "#f97316" }, { label: "Declining", min: -20, color: "#ef4444" }] },
      { id: "roic", label: "ROIC", description: "Return on invested capital — capital allocation quality", unit: "%", min: 0, max: 40, step: 0.5, score: v => v >= 18 ? 5 : v >= 12 ? 4 : v >= 8 ? 3 : v >= 5 ? 2 : 1, bands: [{ label: "Wide moat economics", min: 18, color: "#38bdf8" }, { label: "Strong", min: 12, color: "#7dd3fc" }, { label: "Acceptable", min: 8, color: "#fbbf24" }, { label: "Weak", min: 5, color: "#f97316" }, { label: "Destroying value", min: 0, color: "#ef4444" }] },
      { id: "operatingMargin", label: "Operating Margin", description: " EBIT margin — operating leverage", unit: "%", min: -10, max: 45, step: 0.5, score: v => v >= 25 ? 5 : v >= 18 ? 4 : v >= 12 ? 3 : v >= 6 ? 2 : 1, bands: [{ label: "Elite", min: 25, color: "#38bdf8" }, { label: "Strong", min: 18, color: "#7dd3fc" }, { label: "Solid", min: 12, color: "#fbbf24" }, { label: "Thin", min: 6, color: "#f97316" }, { label: "Unprofitable ops", min: -10, color: "#ef4444" }] },
      { id: "netDebtEbitda", label: "Net Debt / EBITDA", description: "Leverage — key credit screen", unit: "x", min: 0, max: 6, step: 0.1, inverted: true, score: v => v <= 0.5 ? 5 : v <= 1.5 ? 4 : v <= 2.5 ? 3 : v <= 3.5 ? 2 : 1, bands: [{ label: "Net cash", max: 0.5, color: "#38bdf8" }, { label: "Conservative", max: 1.5, color: "#7dd3fc" }, { label: "Normal", max: 2.5, color: "#fbbf24" }, { label: "Elevated", max: 3.5, color: "#f97316" }, { label: "Stressed", max: 99, color: "#ef4444" }] },
      { id: "fcfYield", label: "FCF Yield", description: "Free cash flow ÷ market cap", unit: "%", min: 0, max: 20, step: 0.25, score: v => v >= 8 ? 5 : v >= 5 ? 4 : v >= 3 ? 3 : v >= 1.5 ? 2 : 1, bands: [{ label: "High cash return", min: 8, color: "#38bdf8" }, { label: "Attractive", min: 5, color: "#7dd3fc" }, { label: "Fair", min: 3, color: "#fbbf24" }, { label: "Low", min: 1.5, color: "#f97316" }, { label: "None / burn", min: 0, color: "#ef4444" }] },
      { id: "evEbitda", label: "EV / EBITDA", description: "Enterprise value vs operating cash earnings", unit: "x", min: 2, max: 30, step: 0.5, inverted: true, score: v => v <= 8 ? 5 : v <= 12 ? 4 : v <= 16 ? 3 : v <= 22 ? 2 : 1, bands: [{ label: "Cheap", max: 8, color: "#38bdf8" }, { label: "Reasonable", max: 12, color: "#7dd3fc" }, { label: "Full", max: 16, color: "#fbbf24" }, { label: "Expensive", max: 22, color: "#f97316" }, { label: "Extreme", max: 99, color: "#ef4444" }] },
      { id: "interestCoverage", label: "Interest Coverage", description: "EBIT ÷ interest expense", unit: "x", min: 0, max: 25, step: 0.5, score: v => v >= 10 ? 5 : v >= 6 ? 4 : v >= 3 ? 3 : v >= 1.5 ? 2 : 1, bands: [{ label: "Fortress", min: 10, color: "#38bdf8" }, { label: "Comfortable", min: 6, color: "#7dd3fc" }, { label: "Adequate", min: 3, color: "#fbbf24" }, { label: "Tight", min: 1.5, color: "#f97316" }, { label: "Distress risk", min: 0, color: "#ef4444" }] },
      { id: "earningsQuality", label: "Earnings Quality", description: "FCF vs reported earnings — accruals risk", type: "select", options: [{ label: "FCF consistently > net income", value: 5, color: "#38bdf8" }, { label: "FCF tracks earnings", value: 4, color: "#7dd3fc" }, { label: "Occasional gap", value: 3, color: "#fbbf24" }, { label: "Frequent accrual-heavy beats", value: 2, color: "#f97316" }, { label: "Red flag quality", value: 1, color: "#ef4444" }] },
      { id: "estimateTrend", label: "Estimate Revisions (90d)", description: "Consensus EPS direction — broker momentum", type: "select", options: [{ label: "Material upgrades", value: 5, color: "#38bdf8" }, { label: "Slight upgrades", value: 4, color: "#7dd3fc" }, { label: "Stable", value: 3, color: "#fbbf24" }, { label: "Downgrades", value: 2, color: "#f97316" }, { label: "Sharp cuts / resets", value: 1, color: "#ef4444" }] },
      { id: "moatQuality", label: "Competitive Moat", description: "Durability of advantage — qualitative desk view", type: "select", options: [{ label: "Wide / structural moat", value: 5, color: "#38bdf8" }, { label: "Narrow but durable", value: 4, color: "#7dd3fc" }, { label: "Average", value: 3, color: "#fbbf24" }, { label: "Commoditised", value: 2, color: "#f97316" }, { label: "Disrupted / eroding", value: 1, color: "#ef4444" }] },
    ],
  },
  tech: {
    id: "tech", label: "Tech Growth", accent: "#6366f1", accentDim: "#312e81", icon: "◈",
    tagline: "Revenue momentum, margin expansion, runway",
    metrics: [
      { id: "revenueGrowth", label: "Revenue Growth (YoY)", description: "Year-on-year top-line growth rate", unit: "%", min: -10, max: 100, step: 0.5, score: v => v >= 40 ? 5 : v >= 25 ? 4 : v >= 15 ? 3 : v >= 5 ? 2 : 1, bands: [{ label: "Hyper-growth", min: 40, color: "#6366f1" }, { label: "Strong", min: 25, color: "#818cf8" }, { label: "Healthy", min: 15, color: "#fbbf24" }, { label: "Slowing", min: 5, color: "#f97316" }, { label: "Stalled", min: -10, color: "#ef4444" }] },
      { id: "grossMargin", label: "Gross Margin", description: "Higher = more scalable business model", unit: "%", min: 0, max: 100, step: 0.5, score: v => v >= 70 ? 5 : v >= 55 ? 4 : v >= 40 ? 3 : v >= 25 ? 2 : 1, bands: [{ label: "Software-like", min: 70, color: "#6366f1" }, { label: "Strong", min: 55, color: "#818cf8" }, { label: "Adequate", min: 40, color: "#fbbf24" }, { label: "Compressed", min: 25, color: "#f97316" }, { label: "Thin", min: 0, color: "#ef4444" }] },
      { id: "ruleof40", label: "Rule of 40", description: "Revenue growth % + profit margin %", unit: "", min: -20, max: 100, step: 1, score: v => v >= 60 ? 5 : v >= 40 ? 4 : v >= 25 ? 3 : v >= 10 ? 2 : 1, bands: [{ label: "Elite", min: 60, color: "#6366f1" }, { label: "Passes", min: 40, color: "#818cf8" }, { label: "Below bar", min: 25, color: "#fbbf24" }, { label: "Weak", min: 10, color: "#f97316" }, { label: "Failing", min: -20, color: "#ef4444" }] },
      { id: "cashRunway", label: "Cash Runway", description: "Months of cash at current burn rate", unit: " mo", min: 0, max: 60, step: 1, score: v => v >= 36 ? 5 : v >= 24 ? 4 : v >= 18 ? 3 : v >= 12 ? 2 : 1, bands: [{ label: "No risk", min: 36, color: "#6366f1" }, { label: "Comfortable", min: 24, color: "#818cf8" }, { label: "Manageable", min: 18, color: "#fbbf24" }, { label: "Watch closely", min: 12, color: "#f97316" }, { label: "Dilution risk", min: 0, color: "#ef4444" }], note: "Set to 60 if already profitable" },
      { id: "psRatio", label: "Price / Sales Ratio", description: "Valuation relative to revenue", unit: "x", min: 0, max: 40, step: 0.5, inverted: true, score: v => v <= 5 ? 5 : v <= 10 ? 4 : v <= 20 ? 3 : v <= 30 ? 2 : 1, bands: [{ label: "Cheap", max: 5, color: "#6366f1" }, { label: "Reasonable", max: 10, color: "#818cf8" }, { label: "Priced for growth", max: 20, color: "#fbbf24" }, { label: "Expensive", max: 30, color: "#f97316" }, { label: "Priced to perfection", max: 99, color: "#ef4444" }] },
      { id: "netRevenueRetention", label: "Net Revenue Retention", description: "% of recurring revenue retained + expanded", unit: "%", min: 60, max: 160, step: 1, score: v => v >= 130 ? 5 : v >= 115 ? 4 : v >= 100 ? 3 : v >= 90 ? 2 : 1, bands: [{ label: "Best-in-class", min: 130, color: "#6366f1" }, { label: "Strong", min: 115, color: "#818cf8" }, { label: "Holding", min: 100, color: "#fbbf24" }, { label: "Churning", min: 90, color: "#f97316" }, { label: "Declining base", min: 60, color: "#ef4444" }], note: "SaaS only. Set to 100 if not applicable." },
      { id: "insiderOwnership", label: "Insider Ownership", description: "% of shares held by founders / management", unit: "%", min: 0, max: 80, step: 0.5, score: v => v >= 20 ? 5 : v >= 10 ? 4 : v >= 5 ? 3 : v >= 2 ? 2 : 1, bands: [{ label: "Skin in game", min: 20, color: "#6366f1" }, { label: "Aligned", min: 10, color: "#818cf8" }, { label: "Moderate", min: 5, color: "#fbbf24" }, { label: "Low", min: 2, color: "#f97316" }, { label: "Negligible", min: 0, color: "#ef4444" }] },
      { id: "forwardPE", label: "Forward P/E", description: "NTM earnings multiple", unit: "x", min: 5, max: 80, step: 0.5, inverted: true, score: v => v <= 18 ? 5 : v <= 28 ? 4 : v <= 40 ? 3 : v <= 55 ? 2 : 1, bands: [{ label: "Reasonable", max: 18, color: "#6366f1" }, { label: "Growth priced", max: 28, color: "#818cf8" }, { label: "Full", max: 40, color: "#fbbf24" }, { label: "Expensive", max: 55, color: "#f97316" }, { label: "Extreme", max: 99, color: "#ef4444" }] },
      { id: "epsGrowth", label: "EPS Growth (YoY)", description: "Earnings momentum", unit: "%", min: -30, max: 80, step: 0.5, score: v => v >= 30 ? 5 : v >= 18 ? 4 : v >= 10 ? 3 : v >= 0 ? 2 : 1, bands: [{ label: "Hyper", min: 30, color: "#6366f1" }, { label: "Strong", min: 18, color: "#818cf8" }, { label: "OK", min: 10, color: "#fbbf24" }, { label: "Flat", min: 0, color: "#f97316" }, { label: "Falling", min: -30, color: "#ef4444" }] },
      { id: "roic", label: "ROIC", description: "Return on invested capital", unit: "%", min: 0, max: 45, step: 0.5, score: v => v >= 20 ? 5 : v >= 14 ? 4 : v >= 9 ? 3 : v >= 5 ? 2 : 1, bands: [{ label: "Excellent", min: 20, color: "#6366f1" }, { label: "Strong", min: 14, color: "#818cf8" }, { label: "OK", min: 9, color: "#fbbf24" }, { label: "Weak", min: 5, color: "#f97316" }, { label: "Poor", min: 0, color: "#ef4444" }] },
      { id: "operatingMargin", label: "Operating Margin", description: "Path to profitability / scale", unit: "%", min: -20, max: 50, step: 0.5, score: v => v >= 25 ? 5 : v >= 15 ? 4 : v >= 8 ? 3 : v >= 0 ? 2 : 1, bands: [{ label: "Best-in-class", min: 25, color: "#6366f1" }, { label: "Strong", min: 15, color: "#818cf8" }, { label: "Improving", min: 8, color: "#fbbf24" }, { label: "Breakeven path", min: 0, color: "#f97316" }, { label: "Burning", min: -20, color: "#ef4444" }] },
      { id: "pegRatio", label: "PEG Ratio", description: "P/E vs growth", unit: "x", min: 0, max: 5, step: 0.05, inverted: true, score: v => v <= 1 ? 5 : v <= 1.5 ? 4 : v <= 2.2 ? 3 : v <= 3 ? 2 : 1, bands: [{ label: "GARP", max: 1, color: "#6366f1" }, { label: "Fair", max: 1.5, color: "#818cf8" }, { label: "Full", max: 2.2, color: "#fbbf24" }, { label: "Rich", max: 3, color: "#f97316" }, { label: "Priced in", max: 99, color: "#ef4444" }] },
    ],
  },
  energy: {
    id: "energy", label: "Energy & Commodities", accent: "#f59e0b", accentDim: "#78350f", icon: "⬡",
    tagline: "Cycle positioning, balance sheet, cost structure",
    metrics: [
      { id: "breakeven", label: "Production Breakeven", description: "Oil price ($/bbl) at cash flow neutral", unit: "$/bbl", min: 20, max: 80, step: 1, inverted: true, score: v => v <= 35 ? 5 : v <= 45 ? 4 : v <= 55 ? 3 : v <= 65 ? 2 : 1, bands: [{ label: "Very low cost", max: 35, color: "#f59e0b" }, { label: "Competitive", max: 45, color: "#fcd34d" }, { label: "Mid-cost", max: 55, color: "#fbbf24" }, { label: "High cost", max: 65, color: "#f97316" }, { label: "Vulnerable", max: 999, color: "#ef4444" }], note: "For renewables, set to 35" },
      { id: "netDebtEbitda", label: "Net Debt / EBITDA", description: "Low debt survives commodity downturns", unit: "x", min: 0, max: 6, step: 0.1, inverted: true, score: v => v <= 0.5 ? 5 : v <= 1.5 ? 4 : v <= 2.5 ? 3 : v <= 4 ? 2 : 1, bands: [{ label: "Net cash", max: 0.5, color: "#f59e0b" }, { label: "Conservative", max: 1.5, color: "#fcd34d" }, { label: "Manageable", max: 2.5, color: "#fbbf24" }, { label: "Stretched", max: 4, color: "#f97316" }, { label: "Cycle risk", max: 99, color: "#ef4444" }] },
      { id: "reserveLife", label: "Reserve Life Index", description: "Years of proven reserves at current production", unit: " yrs", min: 0, max: 30, step: 0.5, score: v => v >= 15 ? 5 : v >= 10 ? 4 : v >= 7 ? 3 : v >= 4 ? 2 : 1, bands: [{ label: "Long-life", min: 15, color: "#f59e0b" }, { label: "Solid", min: 10, color: "#fcd34d" }, { label: "Adequate", min: 7, color: "#fbbf24" }, { label: "Short", min: 4, color: "#f97316" }, { label: "Depleting", min: 0, color: "#ef4444" }], note: "For renewables, set to 20" },
      { id: "fcfYield", label: "FCF Yield", description: "Free cash flow as % of market cap", unit: "%", min: 0, max: 25, step: 0.5, score: v => v >= 12 ? 5 : v >= 8 ? 4 : v >= 5 ? 3 : v >= 2 ? 2 : 1, bands: [{ label: "Exceptional", min: 12, color: "#f59e0b" }, { label: "Strong", min: 8, color: "#fcd34d" }, { label: "Healthy", min: 5, color: "#fbbf24" }, { label: "Thin", min: 2, color: "#f97316" }, { label: "Weak", min: 0, color: "#ef4444" }] },
      { id: "dividendCover", label: "Dividend Coverage (at cycle lows)", description: "Can dividend survive commodity downturn?", type: "select", options: [{ label: "Covered even at $40/bbl", value: 5, color: "#f59e0b" }, { label: "Covered at $50/bbl", value: 4, color: "#fcd34d" }, { label: "Covered at $60/bbl", value: 3, color: "#fbbf24" }, { label: "Requires $70+/bbl", value: 2, color: "#f97316" }, { label: "Dividend at risk", value: 1, color: "#ef4444" }] },
      { id: "esgRisk", label: "Energy Transition Risk", description: "Exposure to stranded asset / regulatory risk", type: "select", options: [{ label: "Renewables-led / diversified", value: 5, color: "#f59e0b" }, { label: "Active transition strategy", value: 4, color: "#fcd34d" }, { label: "Mixed portfolio", value: 3, color: "#fbbf24" }, { label: "Fossil-heavy, limited pivot", value: 2, color: "#f97316" }, { label: "Pure-play coal / heavy oil", value: 1, color: "#ef4444" }] },
      { id: "roace", label: "ROACE", description: "Return on average capital employed", unit: "%", min: 0, max: 30, step: 0.5, score: v => v >= 18 ? 5 : v >= 12 ? 4 : v >= 8 ? 3 : v >= 4 ? 2 : 1, bands: [{ label: "Excellent", min: 18, color: "#f59e0b" }, { label: "Strong", min: 12, color: "#fcd34d" }, { label: "Adequate", min: 8, color: "#fbbf24" }, { label: "Poor", min: 4, color: "#f97316" }, { label: "Value destroyer", min: 0, color: "#ef4444" }] },
      { id: "forwardPE", label: "Forward P/E (cycle-adj)", description: "Use normalised earnings at mid-cycle", unit: "x", min: 3, max: 25, step: 0.5, inverted: true, score: v => v <= 8 ? 5 : v <= 11 ? 4 : v <= 14 ? 3 : v <= 18 ? 2 : 1, bands: [{ label: "Deep value", max: 8, color: "#f59e0b" }, { label: "Fair", max: 11, color: "#fcd34d" }, { label: "Mid-cycle", max: 14, color: "#fbbf24" }, { label: "Cycle high", max: 18, color: "#f97316" }, { label: "Peak earnings trap", max: 99, color: "#ef4444" }] },
      { id: "reserveReplacement", label: "Reserve Replacement Ratio", description: "Adds vs production — sustainability", type: "select", options: [{ label: ">120% consistently", value: 5, color: "#f59e0b" }, { label: "100–120%", value: 4, color: "#fcd34d" }, { label: "~100%", value: 3, color: "#fbbf24" }, { label: "Below 100%", value: 2, color: "#f97316" }, { label: "Depleting asset base", value: 1, color: "#ef4444" }], note: "Renewables: select ~100%." },
    ],
  },
  financial: {
    id: "financial", label: "Financial Services", accent: "#10b981", accentDim: "#064e3b", icon: "▣",
    tagline: "Capital strength, credit quality, earnings power",
    metrics: [
      { id: "tier1Capital", label: "CET1 / Tier 1 Capital Ratio", description: "Core capital as % of risk-weighted assets", unit: "%", min: 8, max: 20, step: 0.1, score: v => v >= 15 ? 5 : v >= 13 ? 4 : v >= 11 ? 3 : v >= 10 ? 2 : 1, bands: [{ label: "Very strong", min: 15, color: "#10b981" }, { label: "Solid", min: 13, color: "#34d399" }, { label: "Adequate", min: 11, color: "#fbbf24" }, { label: "Regulatory minimum", min: 10, color: "#f97316" }, { label: "Under pressure", min: 8, color: "#ef4444" }], note: "For insurers, use Solvency II ÷ 10" },
      { id: "roe", label: "Return on Equity (ROE)", description: "Profitability relative to shareholder equity", unit: "%", min: 0, max: 25, step: 0.5, score: v => v >= 15 ? 5 : v >= 12 ? 4 : v >= 9 ? 3 : v >= 6 ? 2 : 1, bands: [{ label: "Excellent", min: 15, color: "#10b981" }, { label: "Strong", min: 12, color: "#34d399" }, { label: "Acceptable", min: 9, color: "#fbbf24" }, { label: "Weak", min: 6, color: "#f97316" }, { label: "Value trap risk", min: 0, color: "#ef4444" }] },
      { id: "nim", label: "Net Interest Margin", description: "Spread between lending and borrowing rates", unit: "%", min: 0, max: 5, step: 0.05, score: v => v >= 3 ? 5 : v >= 2.5 ? 4 : v >= 2 ? 3 : v >= 1.5 ? 2 : 1, bands: [{ label: "Strong", min: 3, color: "#10b981" }, { label: "Healthy", min: 2.5, color: "#34d399" }, { label: "Adequate", min: 2, color: "#fbbf24" }, { label: "Compressed", min: 1.5, color: "#f97316" }, { label: "Under pressure", min: 0, color: "#ef4444" }], note: "For insurers/asset managers, set to 2.5" },
      { id: "nplRatio", label: "Non-Performing Loan Ratio", description: "% of loan book that is impaired", unit: "%", min: 0, max: 10, step: 0.1, inverted: true, score: v => v <= 1 ? 5 : v <= 2 ? 4 : v <= 3.5 ? 3 : v <= 5 ? 2 : 1, bands: [{ label: "Clean book", max: 1, color: "#10b981" }, { label: "Healthy", max: 2, color: "#34d399" }, { label: "Watch", max: 3.5, color: "#fbbf24" }, { label: "Elevated", max: 5, color: "#f97316" }, { label: "Stress", max: 99, color: "#ef4444" }] },
      { id: "efficiencyRatio", label: "Cost / Income Ratio", description: "Operating costs as % of income", unit: "%", min: 30, max: 90, step: 1, inverted: true, score: v => v <= 45 ? 5 : v <= 55 ? 4 : v <= 65 ? 3 : v <= 75 ? 2 : 1, bands: [{ label: "Lean", max: 45, color: "#10b981" }, { label: "Efficient", max: 55, color: "#34d399" }, { label: "Industry avg", max: 65, color: "#fbbf24" }, { label: "Bloated", max: 75, color: "#f97316" }, { label: "Restructuring needed", max: 999, color: "#ef4444" }] },
      { id: "pbRatio", label: "Price / Book Ratio", description: "Market value vs book value", unit: "x", min: 0, max: 3, step: 0.05, inverted: true, score: v => v <= 0.8 ? 5 : v <= 1.2 ? 4 : v <= 1.8 ? 3 : v <= 2.5 ? 2 : 1, bands: [{ label: "Deep value", max: 0.8, color: "#10b981" }, { label: "Fair value", max: 1.2, color: "#34d399" }, { label: "Slight premium", max: 1.8, color: "#fbbf24" }, { label: "Expensive", max: 2.5, color: "#f97316" }, { label: "Overvalued", max: 99, color: "#ef4444" }] },
      { id: "dividendCoverage", label: "Dividend Payout Ratio", description: "% of earnings paid as dividends", unit: "%", min: 0, max: 100, step: 1, inverted: true, score: v => v <= 40 ? 5 : v <= 55 ? 4 : v <= 70 ? 3 : v <= 85 ? 2 : 1, bands: [{ label: "Conservative", max: 40, color: "#10b981" }, { label: "Healthy", max: 55, color: "#34d399" }, { label: "Adequate", max: 70, color: "#fbbf24" }, { label: "Stretched", max: 85, color: "#f97316" }, { label: "Unsustainable", max: 999, color: "#ef4444" }] },
      { id: "ptbv", label: "Price / Tangible Book", description: "Especially for banks — franchise vs asset value", unit: "x", min: 0, max: 3.5, step: 0.05, inverted: true, score: v => v <= 0.9 ? 5 : v <= 1.3 ? 4 : v <= 1.8 ? 3 : v <= 2.5 ? 2 : 1, bands: [{ label: "Below tangible", max: 0.9, color: "#10b981" }, { label: "Fair", max: 1.3, color: "#34d399" }, { label: "Premium", max: 1.8, color: "#fbbf24" }, { label: "Rich", max: 2.5, color: "#f97316" }, { label: "Franchise priced in", max: 99, color: "#ef4444" }] },
      { id: "creditTrend", label: "Credit / Provisions Trend", description: "Impairment cycle direction", type: "select", options: [{ label: "Releases / improving", value: 5, color: "#10b981" }, { label: "Stable low loss", value: 4, color: "#34d399" }, { label: "Normalising", value: 3, color: "#fbbf24" }, { label: "Building reserves", value: 2, color: "#f97316" }, { label: "Deteriorating book", value: 1, color: "#ef4444" }] },
    ],
  },
  consumer: {
    id: "consumer", label: "Consumer & Industrials", accent: "#f472b6", accentDim: "#831843", icon: "◉",
    tagline: "Brand strength, margins, cash conversion, dividend safety",
    metrics: [
      { id: "revenueGrowth", label: "Revenue Growth (YoY)", description: "Organic volume + price", unit: "%", min: -10, max: 25, step: 0.5, score: v => v >= 12 ? 5 : v >= 7 ? 4 : v >= 3 ? 3 : v >= 0 ? 2 : 1, bands: [{ label: "Strong", min: 12, color: "#f472b6" }, { label: "Healthy", min: 7, color: "#f9a8d4" }, { label: "Steady", min: 3, color: "#fbbf24" }, { label: "Flat", min: 0, color: "#f97316" }, { label: "Declining", min: -10, color: "#ef4444" }] },
      { id: "grossMargin", label: "Gross Margin", description: "Pricing power indicator", unit: "%", min: 10, max: 70, step: 0.5, score: v => v >= 45 ? 5 : v >= 35 ? 4 : v >= 28 ? 3 : v >= 20 ? 2 : 1, bands: [{ label: "Premium brand", min: 45, color: "#f472b6" }, { label: "Strong", min: 35, color: "#f9a8d4" }, { label: "Average", min: 28, color: "#fbbf24" }, { label: "Pressure", min: 20, color: "#f97316" }, { label: "Commodity", min: 10, color: "#ef4444" }] },
      { id: "roic", label: "ROIC", description: "Capital efficiency", unit: "%", min: 0, max: 35, step: 0.5, score: v => v >= 16 ? 5 : v >= 12 ? 4 : v >= 8 ? 3 : v >= 5 ? 2 : 1, bands: [{ label: "Excellent", min: 16, color: "#f472b6" }, { label: "Strong", min: 12, color: "#f9a8d4" }, { label: "OK", min: 8, color: "#fbbf24" }, { label: "Weak", min: 5, color: "#f97316" }, { label: "Poor", min: 0, color: "#ef4444" }] },
      { id: "forwardPE", label: "Forward P/E", description: "Valuation vs staples/industrial peers", unit: "x", min: 8, max: 35, step: 0.5, inverted: true, score: v => v <= 14 ? 5 : v <= 18 ? 4 : v <= 22 ? 3 : v <= 28 ? 2 : 1, bands: [{ label: "Value", max: 14, color: "#f472b6" }, { label: "Fair", max: 18, color: "#f9a8d4" }, { label: "Full", max: 22, color: "#fbbf24" }, { label: "Premium", max: 28, color: "#f97316" }, { label: "Stretched", max: 99, color: "#ef4444" }] },
      { id: "fcfYield", label: "FCF Yield", description: "Cash returned to owners potential", unit: "%", min: 0, max: 12, step: 0.25, score: v => v >= 6 ? 5 : v >= 4 ? 4 : v >= 2.5 ? 3 : v >= 1.5 ? 2 : 1, bands: [{ label: "High", min: 6, color: "#f472b6" }, { label: "Good", min: 4, color: "#f9a8d4" }, { label: "Fair", min: 2.5, color: "#fbbf24" }, { label: "Low", min: 1.5, color: "#f97316" }, { label: "Weak", min: 0, color: "#ef4444" }] },
      { id: "dividendYield", label: "Dividend Yield", description: "Income — very high yield may signal cut risk", unit: "%", min: 0, max: 10, step: 0.1, score: v => { if (v > 6) return 1; if (v >= 3 && v <= 5) return 5; if (v >= 2) return 4; if (v >= 1) return 3; return 2; }, bands: [{ label: "Sweet spot (3–5%)", min: 3, color: "#f472b6" }, { label: "Attractive", min: 2, color: "#f9a8d4" }, { label: "Modest", min: 1, color: "#fbbf24" }, { label: "Low / none", min: 0, color: "#64748b" }] },
      { id: "netDebtEbitda", label: "Net Debt / EBITDA", description: "Balance sheet for cyclicals", unit: "x", min: 0, max: 5, step: 0.1, inverted: true, score: v => v <= 1 ? 5 : v <= 2 ? 4 : v <= 2.8 ? 3 : v <= 3.5 ? 2 : 1, bands: [{ label: "Strong", max: 1, color: "#f472b6" }, { label: "OK", max: 2, color: "#f9a8d4" }, { label: "Watch", max: 2.8, color: "#fbbf24" }, { label: "Levered", max: 3.5, color: "#f97316" }, { label: "Risk", max: 99, color: "#ef4444" }] },
      { id: "brandMoat", label: "Brand / Pricing Power", description: "Qualitative — shelf space, loyalty", type: "select", options: [{ label: "Dominant brand", value: 5, color: "#f472b6" }, { label: "Strong share", value: 4, color: "#f9a8d4" }, { label: "Average", value: 3, color: "#fbbf24" }, { label: "Private label pressure", value: 2, color: "#f97316" }, { label: "No moat", value: 1, color: "#ef4444" }] },
    ],
  },
  healthcare: {
    id: "healthcare", label: "Healthcare & Pharma", accent: "#a78bfa", accentDim: "#4c1d95", icon: "✚",
    tagline: "Pipeline, margins, patent cliff, regulatory risk",
    metrics: [
      { id: "revenueGrowth", label: "Revenue Growth (YoY)", description: "Launch curve + portfolio mix", unit: "%", min: -10, max: 30, step: 0.5, score: v => v >= 15 ? 5 : v >= 8 ? 4 : v >= 3 ? 3 : v >= 0 ? 2 : 1, bands: [{ label: "Strong", min: 15, color: "#a78bfa" }, { label: "Healthy", min: 8, color: "#c4b5fd" }, { label: "Steady", min: 3, color: "#fbbf24" }, { label: "Flat", min: 0, color: "#f97316" }, { label: "Declining", min: -10, color: "#ef4444" }] },
      { id: "grossMargin", label: "Gross Margin", description: "Mix of innovator vs generic", unit: "%", min: 30, max: 90, step: 0.5, score: v => v >= 75 ? 5 : v >= 65 ? 4 : v >= 55 ? 3 : v >= 45 ? 2 : 1, bands: [{ label: "Innovator-like", min: 75, color: "#a78bfa" }, { label: "Strong", min: 65, color: "#c4b5fd" }, { label: "Mixed", min: 55, color: "#fbbf24" }, { label: "Generic-heavy", min: 45, color: "#f97316" }, { label: "Compressed", min: 30, color: "#ef4444" }] },
      { id: "rdIntensity", label: "R&D / Sales", description: "Reinvestment in pipeline", unit: "%", min: 0, max: 35, step: 0.5, score: v => v >= 18 && v <= 25 ? 5 : v >= 12 ? 4 : v >= 8 ? 3 : v >= 4 ? 2 : 1, bands: [{ label: "Innovator band", min: 18, color: "#a78bfa" }, { label: "Solid", min: 12, color: "#c4b5fd" }, { label: "Moderate", min: 8, color: "#fbbf24" }, { label: "Light R&D", min: 4, color: "#f97316" }, { label: "Minimal", min: 0, color: "#64748b" }] },
      { id: "forwardPE", label: "Forward P/E", description: "Valuation vs growth + pipeline", unit: "x", min: 8, max: 45, step: 0.5, inverted: true, score: v => v <= 15 ? 5 : v <= 20 ? 4 : v <= 28 ? 3 : v <= 35 ? 2 : 1, bands: [{ label: "Attractive", max: 15, color: "#a78bfa" }, { label: "Fair", max: 20, color: "#c4b5fd" }, { label: "Full", max: 28, color: "#fbbf24" }, { label: "Rich", max: 35, color: "#f97316" }, { label: "Stretched", max: 99, color: "#ef4444" }] },
      { id: "fcfYield", label: "FCF Yield", description: "Cash after R&D and capex", unit: "%", min: 0, max: 12, step: 0.25, score: v => v >= 5 ? 5 : v >= 3.5 ? 4 : v >= 2 ? 3 : v >= 1 ? 2 : 1, bands: [{ label: "Strong", min: 5, color: "#a78bfa" }, { label: "Good", min: 3.5, color: "#c4b5fd" }, { label: "Fair", min: 2, color: "#fbbf24" }, { label: "Thin", min: 1, color: "#f97316" }, { label: "Weak", min: 0, color: "#ef4444" }] },
      { id: "netDebtEbitda", label: "Net Debt / EBITDA", description: "M&A / litigation buffer", unit: "x", min: 0, max: 5, step: 0.1, inverted: true, score: v => v <= 1 ? 5 : v <= 2 ? 4 : v <= 3 ? 3 : v <= 4 ? 2 : 1, bands: [{ label: "Strong", max: 1, color: "#a78bfa" }, { label: "OK", max: 2, color: "#c4b5fd" }, { label: "Elevated", max: 3, color: "#fbbf24" }, { label: "High", max: 4, color: "#f97316" }, { label: "Stressed", max: 99, color: "#ef4444" }] },
      { id: "pipelineStrength", label: "Pipeline / Patent Cliff", description: "Next 3–5y revenue visibility", type: "select", options: [{ label: "Blockbusters + long exclusivity", value: 5, color: "#a78bfa" }, { label: "Solid pipeline", value: 4, color: "#c4b5fd" }, { label: "Mixed cliff", value: 3, color: "#fbbf24" }, { label: "Major LOE soon", value: 2, color: "#f97316" }, { label: "Cliff imminent", value: 1, color: "#ef4444" }] },
      { id: "regulatoryRisk", label: "Regulatory / Reimbursement", description: "FDA / NICE / pricing pressure", type: "select", options: [{ label: "Low visibility risk", value: 5, color: "#a78bfa" }, { label: "Manageable", value: 4, color: "#c4b5fd" }, { label: "Average", value: 3, color: "#fbbf24" }, { label: "Headline risk", value: 2, color: "#f97316" }, { label: "Severe overhang", value: 1, color: "#ef4444" }] },
    ],
  },
};

export const getRating = avg => {
  if (avg >= 4.5) return { label: "Strong Buy", short: "SB" };
  if (avg >= 3.5) return { label: "Buy", short: "B" };
  if (avg >= 2.5) return { label: "Hold", short: "H" };
  if (avg >= 1.5) return { label: "Sell", short: "S" };
  return { label: "Strong Sell", short: "SS" };
};

export const getRatingColor = (avg, accent) => {
  if (avg >= 4.5) return accent;
  if (avg >= 3.5) return accent + "cc";
  if (avg >= 2.5) return "#fbbf24";
  if (avg >= 1.5) return "#f97316";
  return "#ef4444";
};

export const getBand = (metric, value) => {
  if (metric.type === "select") return metric.options.find(o => o.value === value) || null;
  if (metric.inverted) {
    const sorted = [...metric.bands].sort((a, b) => (a.max ?? 99) - (b.max ?? 99));
    return sorted.find(b => value <= (b.max ?? 99)) || sorted[sorted.length - 1];
  }
  const sorted = [...metric.bands].sort((a, b) => b.min - a.min);
  return sorted.find(b => value >= b.min) || sorted[sorted.length - 1];
};

export const getScore = (metric, value) => metric.type === "select" ? value : metric.score(value);
export const defaultValues = metrics => Object.fromEntries(metrics.map(m => [m.id, m.type === "select" ? 3 : parseFloat(((m.max - m.min) / 2 + m.min).toFixed(1))]));

export function mergeMetricValues(sectorId, values = {}) {
  const sector = SECTORS[sectorId];
  if (!sector) return { ...values };
  return { ...defaultValues(sector.metrics), ...values };
}

export const calcAvg = (metrics, values) => {
  const defaults = defaultValues(metrics);
  const scores = metrics.map((m) => getScore(m, values[m.id] ?? defaults[m.id]));
  return scores.reduce((a, b) => a + b, 0) / scores.length;
};

export function emptySectorValuesMap() {
  return Object.fromEntries(
    Object.entries(SECTORS).map(([id, sector]) => [id, defaultValues(sector.metrics)]),
  );
}

export function emptySectorNamesMap() {
  return Object.fromEntries(Object.keys(SECTORS).map((id) => [id, ""]));
}
